# -*- coding: utf-8 -*-
"""ecosense_iot_optimization_v2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v0Sozy_0-VWotqbvMnnp3k31mUBt_Z6V
"""

# =============================================================================
# Team EcoSense: IoT-Energy Optimization Twin  ── VERSION 2.0
# Fokus: Efisiensi energi pabrik manufaktur (AHM - Tantangan #1)
#
# UPGRADE dari v1:
# ─────────────────────────────────────────────────────────────────────────────
# [DATA]   Multi-mesin (3 mesin), variabel lingkungan (ambient temp, humidity),
#          efisiensi mesin progresif, pola 3-shift realistis
# [ML]     VotingRegressor ensemble (Ridge + RandomForest + HGB) ganti model tunggal
# [XAI]    Permutation Importance sebagai SHAP proxy – setiap fitur bisa dijelaskan
# [ANOM]   Ensemble 3 detektor (IsolationForest + LOF + Z-Score robust) + voting
#          → precision/recall vs ground truth dihitung otomatis
# [SPC]    Tambah CUSUM & EWMA chart di atas X-bar/S tradisional
#          CUSUM: sensitif pergeseran kecil | EWMA: sensitif tren bertahap
# [OPT]    NSGA-II multi-objective via DEAP (minimize energi + maximize produksi)
#          → menghasilkan Pareto front, fallback grid-Pareto jika DEAP tidak ada
# [STREAM] Streaming Alert Engine dengan rolling window & 3 jenis alert real-time
# [VIZ]    Dashboard 12 panel dengan tema industrial dark
# =============================================================================
# !pip install deap
# !pip install prophet
from __future__ import annotations

import json
import warnings
from collections import deque
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from scipy import stats, optimize
from sklearn.ensemble import (
    HistGradientBoostingRegressor,
    IsolationForest,
    RandomForestRegressor,
    VotingRegressor,
)
from sklearn.linear_model import RidgeCV
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.model_selection import TimeSeriesSplit
from sklearn.neighbors import LocalOutlierFactor
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, PowerTransformer
from sklearn.inspection import permutation_importance

warnings.filterwarnings("ignore")

# !pip install scikit-learn scipy pandas numpy matplotlib


# ─────────────────────────────────────────────────────────────────
# KONFIGURASI
# ─────────────────────────────────────────────────────────────────

@dataclass
class EcoSenseConfig:
    n_samples: int = 2016          # 7 hari × 288 titik/hari @ 5 menit
    interval_sec: int = 300
    n_machines: int = 3
    anomaly_contamination: float = 0.05
    spc_subgroup_size: int = 7
    energy_tariff_idr: float = 1_500.0
    annual_hours: int = 8_000
    output_dir: Path = Path("ecosense_output")

    def __post_init__(self):
        self.output_dir.mkdir(parents=True, exist_ok=True)


CFG = EcoSenseConfig()


# ─────────────────────────────────────────────────────────────────
# MODUL 1: SIMULASI DATA IoT (UPGRADE)
# ─────────────────────────────────────────────────────────────────

def generate_iot_sensor_data(
    n_samples: int = CFG.n_samples,
    interval_seconds: int = CFG.interval_sec,
    n_machines: int = CFG.n_machines,
    seed: int = 42,
) -> pd.DataFrame:
    """
    [UPGRADE v2] Mensimulasikan data IoT multi-mesin selama 7 hari.

    Variabel Sensor (diperluas dari v1):
    - X_Temp           : Suhu operasional mesin (°C)
    - X_Load           : Beban mesin (% kapasitas)
    - X_RPM            : Kecepatan rotasi (RPM)
    - X_Ambient_Temp   : [BARU] Suhu lingkungan pabrik (°C)
    - X_Humidity       : [BARU] Kelembaban udara (%)
    - X_Efficiency     : [BARU] Efisiensi mesin (degradasi bertahap)
    - Y_energy_kWh     : Konsumsi energi aktual

    Pola Simulasi (diperluas dari v1):
    - 3 shift 8-jam (bukan 2 shift seperti v1)
    - Weekend: produksi 50% (baru)
    - Degradasi efisiensi mesin + recovery setelah maintenance (baru)
    - 3 tipe anomali: spike, drop, drift bertahap (v1 hanya spike/drop)
    """
    np.random.seed(seed)
    n = n_samples

    timestamps = pd.date_range(
        start="2024-01-08 00:00:00", periods=n, freq=f"{interval_seconds}s"
    )
    hours = np.array([t.hour + t.minute / 60 for t in timestamps])
    days  = np.array([t.dayofweek for t in timestamps])

    all_records = []

    for machine_id in range(1, n_machines + 1):
        np.random.seed(seed + machine_id * 100)

        # --- Variabel Lingkungan (baru) ---
        ambient_temp = (28 + 6 * np.sin(2 * np.pi * hours / 24 - np.pi)
                        + np.random.normal(0, 0.8, n))
        humidity = (65 + 15 * np.sin(2 * np.pi * hours / 24)
                    + np.random.normal(0, 3, n))
        ambient_temp = np.clip(ambient_temp, 20, 42)
        humidity     = np.clip(humidity, 40, 95)

        # --- Pola 3 Shift Realistis (upgrade dari 2 shift) ---
        def shift_load(h):
            if   6 <= h < 14: return 75   # Shift 1: pagi
            elif 14 <= h < 22: return 88  # Shift 2: siang (paling sibuk)
            else:               return 45 # Shift 3: malam (maintenance parsial)

        base_load      = np.vectorize(shift_load)(hours)
        weekend_factor = np.where(days >= 5, 0.5, 1.0)       # Weekend 50%
        machine_factor = 1.0 + (machine_id - 1) * 0.08       # M2/M3 sedikit lebih berat

        X_Load = (base_load * weekend_factor * machine_factor
                  + np.random.normal(0, 4, n))
        X_Load = np.clip(X_Load, 20, 100)

        # --- Suhu Mesin (terpengaruh beban + ambient) ---
        X_Temp = (55 + 0.3 * X_Load + 0.4 * (ambient_temp - 28)
                  + 8 * np.sin(2 * np.pi * hours / 16)
                  + np.random.normal(0, 2, n))
        X_Temp = np.clip(X_Temp, 45, 115)

        # --- RPM ---
        X_RPM = 1100 + 10 * X_Load + np.random.normal(0, 40, n)
        X_RPM = np.clip(X_RPM, 700, 2400)

        # --- Efisiensi Mesin (degradasi + recovery maintenance – baru) ---
        efficiency = 1.0 - (np.arange(n) / n) * 0.04
        efficiency[int(n * 0.72):] += 0.025  # recovery setelah maintenance
        efficiency = np.clip(efficiency, 0.92, 1.02)

        # --- Model Konsumsi Energi (diperluas dari v1) ---
        beta = [9.8, 0.09, 0.38, 0.0045, 0.015, -0.08]
        noise = np.random.normal(0, 1.2, n)
        Y = (beta[0]
             + beta[1] * X_Temp
             + beta[2] * X_Load
             + beta[3] * X_RPM
             + beta[4] * ambient_temp
             + beta[5] * humidity / 100
             + noise) / efficiency

        # --- Anomali: 3 tipe (upgrade dari 2 tipe di v1) ---
        n_anom = int(0.04 * n)
        anom_idx = np.random.choice(n, size=n_anom, replace=False)
        anom_labels = np.zeros(n, dtype=bool)
        anom_types = np.random.choice(
            ["spike", "drop", "drift"], size=n_anom, p=[0.5, 0.3, 0.2]
        )
        for idx, atype in zip(anom_idx, anom_types):
            if atype == "spike":
                Y[idx] *= np.random.uniform(1.5, 2.0)
            elif atype == "drop":
                Y[idx] *= np.random.uniform(0.3, 0.55)
            else:  # drift: 5 titik bertahap
                end = min(idx + 5, n)
                Y[idx:end] += np.linspace(3, 8, end - idx)
            anom_labels[idx] = True

        for i in range(n):
            all_records.append({
                "timestamp":      timestamps[i],
                "machine_id":     f"M{machine_id:02d}",
                "X_Temp":         round(float(X_Temp[i]), 2),
                "X_Load":         round(float(X_Load[i]), 2),
                "X_RPM":          round(float(X_RPM[i]), 1),
                "X_Ambient_Temp": round(float(ambient_temp[i]), 2),
                "X_Humidity":     round(float(humidity[i]), 2),
                "X_Efficiency":   round(float(efficiency[i]), 4),
                "Y_energy_kWh":   round(float(max(0, Y[i])), 3),
                "is_anomaly_true": bool(anom_labels[i]),
                "shift":          int(1 if 6 <= hours[i] < 14
                                     else 2 if 14 <= hours[i] < 22 else 3),
                "is_weekend":     bool(days[i] >= 5),
            })

    df = pd.DataFrame(all_records)
    total_anom = df["is_anomaly_true"].sum()
    print("✅ Dataset IoT Sensor Multi-Mesin berhasil dibuat.")
    print(f"   Total data points : {len(df):,} ({n_machines} mesin × {n_samples} sampel)")
    print(f"   Durasi            : {n_samples * interval_seconds / 3600:.1f} jam (7 hari)")
    print(f"   Anomali injeksi   : {total_anom} ({total_anom/len(df)*100:.1f}%)")
    print(f"   Fitur sensor      : 6 variabel (v1: 3 variabel)\n")
    return df


def summarize_data_health(df: pd.DataFrame) -> pd.DataFrame:
    """Ringkasan kualitas data IoT per mesin."""
    cols = ["X_Temp", "X_Load", "X_RPM", "X_Ambient_Temp", "X_Humidity", "Y_energy_kWh"]
    rows = []
    for mid in df["machine_id"].unique():
        mdf = df[df["machine_id"] == mid]
        for col in cols:
            row = mdf[col].describe().to_dict()
            row["machine_id"] = mid
            row["column"] = col
            row["missing_pct"] = mdf[col].isna().mean() * 100
            rows.append(row)
    return pd.DataFrame(rows)


# ─────────────────────────────────────────────────────────────────
# MODUL 2: ENSEMBLE ENERGY MODEL (UPGRADE)
# ─────────────────────────────────────────────────────────────────

def build_energy_model(
    df: pd.DataFrame,
    machine_id: str = "M01",
    test_split: float = 0.2,
) -> dict:
    """
    [UPGRADE v2] VotingRegressor: Ridge + RandomForest + HGB.
    - v1 menggunakan seleksi model tunggal terbaik
    - v2 menggabungkan ketiganya via ensemble voting
    - Tambah Permutation Importance (XAI proxy) menggantikan coef_ sederhana
    - Fitur diperluas dari 3 → 6 variabel
    """
    mdf = df[df["machine_id"] == machine_id].copy().reset_index(drop=True)

    features = ["X_Temp", "X_Load", "X_RPM",
                "X_Ambient_Temp", "X_Humidity", "X_Efficiency"]
    target = "Y_energy_kWh"

    X = mdf[features].values
    y = mdf[target].values

    split_idx = int(len(X) * (1 - test_split))
    X_train, X_test = X[:split_idx], X[split_idx:]
    y_train, y_test = y[:split_idx], y[split_idx:]

    scaler = Pipeline([
        ("std", StandardScaler()),
        ("pwr", PowerTransformer(method="yeo-johnson", standardize=True)),
    ])
    X_tr_s = scaler.fit_transform(X_train)
    X_te_s = scaler.transform(X_test)

    # Sub-models
    ridge = RidgeCV(alphas=[0.01, 0.1, 1, 10, 100], cv=TimeSeriesSplit(n_splits=5))
    rf    = RandomForestRegressor(n_estimators=200, max_depth=10,
                                  min_samples_leaf=5, random_state=42, n_jobs=None)
    hgb   = HistGradientBoostingRegressor(max_iter=400, learning_rate=0.05,
                                          max_leaf_nodes=31, l2_regularization=0.1, random_state=42)

    # VotingRegressor ensemble
    ensemble = VotingRegressor(
        estimators=[("ridge", ridge), ("rf", rf), ("hgb", hgb)],
        n_jobs=None,
    )
    ensemble.fit(X_tr_s, y_train)

    y_pred = ensemble.predict(X_te_s)
    r2   = r2_score(y_test, y_pred)
    mae  = mean_absolute_error(y_test, y_pred)
    rmse = float(np.sqrt(np.mean((y_test - y_pred) ** 2)))

    # Permutation Importance (baru – menggantikan coef_ sederhana)
    perm = permutation_importance(ensemble, X_te_s, y_test,
                                  n_repeats=10, random_state=42, n_jobs=-1)
    importance = {
        feat: float(imp)
        for feat, imp in zip(features, perm.importances_mean)
    }

    residuals = y_test - y_pred

    print(f"🔬 [Ensemble Model – {machine_id}] "
          f"R²={r2:.4f} | MAE={mae:.4f} | RMSE={rmse:.4f}")
    print("   Permutation Importance:")
    for k, v in sorted(importance.items(), key=lambda x: -abs(x[1])):
        bar = "█" * int(max(0, v) * 250)
        print(f"   {k:<22}: {v:+.4f}  {bar}")
    print()

    return {
        "model":         ensemble,
        "scaler":        scaler,
        "features":      features,
        "r2_test":       r2,
        "mae_test":      mae,
        "rmse_test":     rmse,
        "y_pred_test":   y_pred,
        "y_test":        y_test,
        "residuals":     residuals,
        "importance":    importance,
        "machine_id":    machine_id,
    }


def predict_energy(model_result: dict, feature_values: dict) -> float:
    """Prediksi konsumsi energi untuk satu kondisi mesin."""
    feats = model_result["features"]
    X = np.array([[feature_values.get(f, 0.0) for f in feats]])
    X_s = model_result["scaler"].transform(X)
    return float(max(0, model_result["model"].predict(X_s)[0]))


# ─────────────────────────────────────────────────────────────────
# MODUL 3: ANOMALY DETECTION ENSEMBLE (UPGRADE)
# ─────────────────────────────────────────────────────────────────

def detect_sensor_anomalies(
    df: pd.DataFrame,
    machine_id: str = "M01",
    contamination: float = CFG.anomaly_contamination,
) -> tuple[pd.DataFrame, dict]:
    """
    [UPGRADE v2] Ensemble 3 detektor dengan majority voting.
    - v1: hanya IsolationForest
    - v2: IsolationForest + LOF + Z-Score robust (MAD) → voting ≥ 2/3
    - Tambah fitur cross-variabel: load/temp ratio, energy/rpm ratio
    - Hitung Precision, Recall, F1 vs ground truth secara otomatis
    """
    mdf = df[df["machine_id"] == machine_id].copy().reset_index(drop=True)

    # Feature engineering temporal
    for col in ["X_Temp", "X_Load", "X_RPM", "Y_energy_kWh"]:
        mdf[f"{col}_diff"]   = mdf[col].diff().fillna(0)
        mdf[f"{col}_roll5"]  = mdf[col].rolling(5, min_periods=1).mean()
        mdf[f"{col}_roll_std"] = mdf[col].rolling(5, min_periods=1).std().fillna(0)
        mdf[f"{col}_ewm"]    = mdf[col].ewm(span=10).mean()

    mdf["load_temp_ratio"] = mdf["X_Load"] / (mdf["X_Temp"] + 1e-6)
    mdf["energy_per_rpm"]  = mdf["Y_energy_kWh"] / (mdf["X_RPM"] + 1e-6)

    feat_cols = (
        ["X_Temp", "X_Load", "X_RPM", "Y_energy_kWh",
         "X_Ambient_Temp", "X_Efficiency"]
        + [c for c in mdf.columns if any(s in c for s in
           ["_diff", "_roll5", "_roll_std", "_ewm", "ratio", "per_rpm"])]
    )
    feat_cols = [c for c in feat_cols if c in mdf.columns]
    X = mdf[feat_cols].fillna(0).values
    X_s = StandardScaler().fit_transform(X)

    # Detektor 1: Isolation Forest
    iforest = IsolationForest(n_estimators=300, contamination=contamination,
                               random_state=42, max_samples="auto")
    iforest_labels = iforest.fit_predict(X_s) == -1
    iforest_scores = -iforest.decision_function(X_s)

    # Detektor 2: Local Outlier Factor (baru)
    lof = LocalOutlierFactor(n_neighbors=20, contamination=contamination, novelty=False)
    lof_labels = lof.fit_predict(X_s) == -1
    lof_scores = -lof.negative_outlier_factor_

    # Detektor 3: Z-Score robust berbasis MAD (baru)
    energy = mdf["Y_energy_kWh"].values
    median_e = np.median(energy)
    mad_e    = np.median(np.abs(energy - median_e)) * 1.4826
    zscore_labels = np.abs(energy - median_e) > 3.5 * (mad_e + 1e-9)
    zscore_scores = np.abs(energy - median_e) / (mad_e + 1e-9)

    # Voting ≥ 2/3 → anomali
    votes = (iforest_labels.astype(int)
             + lof_labels.astype(int)
             + zscore_labels.astype(int))
    ensemble_labels = votes >= 2

    composite_score = (
        iforest_scores / (iforest_scores.max() + 1e-9)
        + lof_scores   / (lof_scores.max()    + 1e-9)
        + zscore_scores / (zscore_scores.max() + 1e-9)
    ) / 3.0

    mdf["anomaly_iforest"]  = iforest_labels
    mdf["anomaly_lof"]      = lof_labels
    mdf["anomaly_zscore"]   = zscore_labels
    mdf["anomaly_ensemble"] = ensemble_labels
    mdf["anomaly_score"]    = composite_score
    mdf["anomaly_votes"]    = votes

    # Precision / Recall / F1 vs ground truth
    true = mdf["is_anomaly_true"].values
    tp = int((ensemble_labels & true).sum())
    fp = int((ensemble_labels & ~true).sum())
    fn = int((~ensemble_labels & true).sum())
    precision = tp / (tp + fp + 1e-9)
    recall    = tp / (tp + fn + 1e-9)
    f1        = 2 * precision * recall / (precision + recall + 1e-9)

    print(f"🔎 [Anomaly Ensemble – {machine_id}]  "
          f"Terdeteksi: {ensemble_labels.sum()} ({ensemble_labels.mean()*100:.1f}%)")
    print(f"   IForest: {iforest_labels.sum()} | "
          f"LOF: {lof_labels.sum()} | Z-Score: {zscore_labels.sum()}")
    print(f"   Precision={precision:.3f} | Recall={recall:.3f} | F1={f1:.3f}\n")

    return mdf, {
        "count":     int(ensemble_labels.sum()),
        "rate":      float(ensemble_labels.mean()),
        "precision": precision,
        "recall":    recall,
        "f1":        f1,
    }


def detect_anomalies_realtime(energy_stream: np.ndarray, spc_result: dict) -> dict:
    """Deteksi anomali point-per-point menggunakan batas SPC."""
    upper = spc_result.get("robust_upper", spc_result["UCL_xbar"])
    lower = spc_result.get("robust_lower", spc_result["LCL_xbar"])
    anomalies = (energy_stream > upper) | (energy_stream < lower)
    return {
        "energy":        energy_stream,
        "anomalies":     anomalies,
        "upper_bound":   upper,
        "lower_bound":   lower,
        "anomaly_count": int(anomalies.sum()),
        "anomaly_rate":  float(anomalies.mean()),
    }


# ─────────────────────────────────────────────────────────────────
# MODUL 4: ADVANCED SPC – CUSUM + EWMA (UPGRADE)
# ─────────────────────────────────────────────────────────────────

def calculate_control_limits(
    data: np.ndarray,
    subgroup_size: int = CFG.spc_subgroup_size,
) -> dict:
    """
    [UPGRADE v2] Tambah CUSUM chart & EWMA chart di samping X-bar/S tradisional.
    - v1: hanya X-bar/S + robust MAD
    - v2: + CUSUM (deteksi pergeseran kecil persisten)
           + EWMA  (deteksi tren bertahap)
    """
    n = subgroup_size

    # Faktor c4 untuk estimasi sigma yang tidak bias
    c4_map = {2:0.7979, 3:0.8862, 4:0.9213, 5:0.9400,
              6:0.9515, 7:0.9594, 8:0.9650, 9:0.9693, 10:0.9727}
    c4 = c4_map.get(n, 0.9594)

    n_complete = (len(data) // n) * n
    subgroups = data[:n_complete].reshape(-1, n)
    xbar = subgroups.mean(axis=1)
    s    = subgroups.std(axis=1, ddof=1)
    xbar_bar = xbar.mean()
    s_bar    = s.mean()
    sigma_est = s_bar / c4

    A3 = 3 / (c4 * np.sqrt(n))
    UCL_xbar = xbar_bar + A3 * s_bar
    LCL_xbar = xbar_bar - A3 * s_bar

    # Robust bounds (MAD)
    med = np.median(data[:n_complete])
    mad = np.median(np.abs(data[:n_complete] - med)) * 1.4826
    robust_upper = med + 3 * mad
    robust_lower = med - 3 * mad
    ooc_xbar = (xbar > UCL_xbar) | (xbar < LCL_xbar)

    # === CUSUM Chart (baru) ===
    k = 0.5 * sigma_est   # reference value
    h = 5.0 * sigma_est   # decision interval
    cusum_pos = np.zeros(len(data))
    cusum_neg = np.zeros(len(data))
    for i in range(1, len(data)):
        cusum_pos[i] = max(0, cusum_pos[i-1] + (data[i] - xbar_bar) - k)
        cusum_neg[i] = max(0, cusum_neg[i-1] - (data[i] - xbar_bar) - k)
    cusum_ooc = (cusum_pos > h) | (cusum_neg > h)

    # === EWMA Chart (baru) ===
    lam = 0.2
    L   = 3.0
    ewma = np.zeros(len(data))
    ewma[0] = data[0]
    for i in range(1, len(data)):
        ewma[i] = lam * data[i] + (1 - lam) * ewma[i-1]
    ewma_sigma = sigma_est * np.sqrt(lam / (2 - lam))
    UCL_ewma = xbar_bar + L * ewma_sigma
    LCL_ewma = xbar_bar - L * ewma_sigma
    ewma_ooc = (ewma > UCL_ewma) | (ewma < LCL_ewma)

    print(f"📊 [Advanced SPC] n={n} per subgroup | σ_est={sigma_est:.3f}")
    print(f"   X-bar  UCL/LCL: {UCL_xbar:.3f} / {LCL_xbar:.3f}  "
          f"OOC: {ooc_xbar.sum()}/{len(xbar)}")
    print(f"   CUSUM  OOC: {cusum_ooc.sum()}/{len(data)}  "
          f"EWMA OOC: {ewma_ooc.sum()}/{len(data)}\n")

    return {
        "xbar": xbar, "s": s,
        "xbar_bar": xbar_bar, "s_bar": s_bar, "sigma_est": sigma_est,
        "UCL_xbar": UCL_xbar, "LCL_xbar": LCL_xbar,
        "ooc_xbar": ooc_xbar,
        "robust_upper": robust_upper, "robust_lower": robust_lower,
        "cusum_pos": cusum_pos, "cusum_neg": cusum_neg,
        "cusum_threshold": h, "cusum_ooc": cusum_ooc,
        "ewma": ewma,
        "UCL_ewma": UCL_ewma, "LCL_ewma": LCL_ewma, "ewma_ooc": ewma_ooc,
        "subgroup_size": n,
    }


# ─────────────────────────────────────────────────────────────────
# MODUL 5: MULTI-OBJECTIVE OPTIMIZATION – NSGA-II (UPGRADE)
# ─────────────────────────────────────────────────────────────────

def optimize_machine_settings(
    model_result: dict,
    temp_bounds: tuple = (55, 90),
    load_bounds: tuple = (50, 95),
    rpm_bounds:  tuple = (1000, 1900),
    n_gen:  int = 80,
    pop_size: int = 100,
) -> dict:
    """
    [UPGRADE v2] Multi-objective optimization dengan NSGA-II (via DEAP).
    - v1: single-objective trust-constr (minimize energi saja)
    - v2: dua objective: minimize energi + maximize production_proxy
          → menghasilkan Pareto front, bukan satu titik optimal saja

    Fallback ke grid Pareto jika DEAP tidak terinstall.

    Install: pip install deap
    """
    try:
        from deap import base, creator, tools, algorithms
        has_deap = True
    except ImportError:
        has_deap = False

    def energy_fn(temp, load, rpm):
        return predict_energy(model_result, {
            "X_Temp": temp, "X_Load": load, "X_RPM": rpm,
            "X_Ambient_Temp": 30.0, "X_Humidity": 70.0, "X_Efficiency": 0.97,
        })

    def production_proxy(load, rpm):
        return load * rpm / 1e5  # production index

    baseline_energy = energy_fn(72.0, 75.0, 1500.0)

    if has_deap:
        # ─── NSGA-II ───
        try:
            creator.create("FitnessMulti2", base.Fitness, weights=(-1.0, +1.0))
            creator.create("Individual2", list, fitness=creator.FitnessMulti2)
        except Exception:
            pass

        toolbox = base.Toolbox()
        toolbox.register("attr_temp", np.random.uniform, *temp_bounds)
        toolbox.register("attr_load", np.random.uniform, *load_bounds)
        toolbox.register("attr_rpm",  np.random.uniform, *rpm_bounds)
        toolbox.register("individual", tools.initCycle, creator.Individual2,
                         (toolbox.attr_temp, toolbox.attr_load, toolbox.attr_rpm), n=1)
        toolbox.register("population", tools.initRepeat, list, toolbox.individual)

        def evaluate(ind):
            t = np.clip(ind[0], *temp_bounds)
            l = np.clip(ind[1], *load_bounds)
            r = np.clip(ind[2], *rpm_bounds)
            return energy_fn(t, l, r), production_proxy(l, r)

        toolbox.register("evaluate", evaluate)
        toolbox.register("mate",   tools.cxSimulatedBinaryBounded,
                         low=[temp_bounds[0], load_bounds[0], rpm_bounds[0]],
                         up= [temp_bounds[1], load_bounds[1], rpm_bounds[1]], eta=20.0)
        toolbox.register("mutate", tools.mutPolynomialBounded,
                         low=[temp_bounds[0], load_bounds[0], rpm_bounds[0]],
                         up= [temp_bounds[1], load_bounds[1], rpm_bounds[1]],
                         eta=20.0, indpb=0.3)
        toolbox.register("select", tools.selNSGA2)

        pop = toolbox.population(n=pop_size)
        algorithms.eaMuPlusLambda(pop, toolbox, mu=pop_size, lambda_=pop_size,
                                   cxpb=0.7, mutpb=0.3, ngen=n_gen,
                                   stats=None, halloffame=None, verbose=False)
        pareto = tools.sortNondominated(pop, len(pop), first_front_only=True)[0]
        pareto_data = [(ind[0], ind[1], ind[2],
                        ind.fitness.values[0], ind.fitness.values[1])
                       for ind in pareto]
        method = "NSGA-II (DEAP)"

    else:
        # ─── Fallback: Grid Pareto ───
        pts = 1000
        temps = np.random.uniform(*temp_bounds, pts)
        loads = np.random.uniform(*load_bounds, pts)
        rpms  = np.random.uniform(*rpm_bounds,  pts)
        all_pts = [(t, l, r, energy_fn(t, l, r), production_proxy(l, r))
                   for t, l, r in zip(temps, loads, rpms)]
        all_pts.sort(key=lambda x: x[3])
        pareto_data, best_p = [], -np.inf
        for pt in all_pts:
            if pt[4] > best_p:
                pareto_data.append(pt)
                best_p = pt[4]
        method = "Grid Pareto (install DEAP untuk NSGA-II: pip install deap)"

    # Pilih titik terbaik: energi terendah dengan produksi ≥ 90% maks
    prod_max = max(p[4] for p in pareto_data)
    valid = [p for p in pareto_data if p[4] >= prod_max * 0.90]
    best  = min(valid or pareto_data, key=lambda x: x[3])

    saving_kwh   = baseline_energy - best[3]
    saving_pct   = saving_kwh / baseline_energy * 100
    annual_kwh   = saving_kwh * CFG.annual_hours
    annual_idr   = annual_kwh * CFG.energy_tariff_idr

    print(f"🎯 [Multi-Obj Optimization] {method}")
    print(f"   Pareto front : {len(pareto_data)} solusi")
    print(f"   Baseline     : {baseline_energy:.3f} kWh")
    print(f"   Optimal      : {best[3]:.3f} kWh  → Hemat {saving_pct:.2f}%")
    print(f"   Hemat tahunan: Rp {annual_idr/1e9:.3f} Miliar\n")

    return {
        "method":             method,
        "pareto_front":       pareto_data,
        "best_point":         {"temp": best[0], "load": best[1], "rpm": best[2],
                               "energy": best[3], "production_index": best[4]},
        "baseline_energy":    baseline_energy,
        "saving_kwh":         saving_kwh,
        "saving_pct":         saving_pct,
        "annual_saving_kwh":  annual_kwh,
        "annual_saving_idr":  annual_idr,
        "current": {"temp": 72.0, "load": 75.0, "rpm": 1500.0, "energy": baseline_energy},
    }


# ─────────────────────────────────────────────────────────────────
# MODUL 6: STRESS TEST (dipertahankan + diperluas)
# ─────────────────────────────────────────────────────────────────

def stress_test_simulation(
    model_result: dict,
    production_increase_pct: int = 20,
) -> pd.DataFrame:
    """Proyeksi kebutuhan energi saat produksi naik X%."""
    print(f"⚡ [Stress Test] Simulasi kenaikan produksi +{production_increase_pct}%")
    scenarios = [0, 10, 20, 30, 50, 75, 100]
    baseline = {"X_Temp": 70.0, "X_Load": 70.0, "X_RPM": 1400.0,
                "X_Ambient_Temp": 30.0, "X_Humidity": 70.0, "X_Efficiency": 0.97}
    results = []
    for inc in scenarios:
        factor = 1 + inc / 100
        fv = {
            "X_Temp":         min(baseline["X_Temp"] + inc * 0.25, 110),
            "X_Load":         min(baseline["X_Load"]  * factor, 100),
            "X_RPM":          min(baseline["X_RPM"]   * factor, 2400),
            "X_Ambient_Temp": baseline["X_Ambient_Temp"],
            "X_Humidity":     baseline["X_Humidity"],
            "X_Efficiency":   max(0.88, baseline["X_Efficiency"] - inc * 0.001),
        }
        energy = predict_energy(model_result, fv)
        results.append({
            "Kenaikan Produksi (%)": inc,
            "Suhu (°C)":   round(fv["X_Temp"], 1),
            "Beban (%)":   round(fv["X_Load"],  1),
            "RPM":         round(fv["X_RPM"],   1),
            "Efisiensi":   round(fv["X_Efficiency"], 3),
            "Energi (kWh)": round(energy, 3),
        })

    df_stress = pd.DataFrame(results)
    base_e = df_stress.iloc[0]["Energi (kWh)"]
    df_stress["Delta Energi (kWh)"] = (df_stress["Energi (kWh)"] - base_e).round(3)
    df_stress["Delta Energi (%)"]   = ((df_stress["Delta Energi (kWh)"] / base_e) * 100).round(2)
    print(df_stress.to_string(index=False))
    print()
    return df_stress


# ─────────────────────────────────────────────────────────────────
# MODUL 7: STREAMING ALERT ENGINE (BARU)
# ─────────────────────────────────────────────────────────────────

class StreamingAlertEngine:
    """
    [BARU v2] Real-time alert engine dengan rolling window.
    3 jenis alert:
    1. SPC Violation  – titik melewati batas robust
    2. EWMA Trend     – EWMA melewati UCL/LCL
    3. Rate-of-Change – lonjakan tiba-tiba antar dua pembacaan
    """

    def __init__(self, spc_result: dict, window_size: int = 60):
        self.spc    = spc_result
        self.window = deque(maxlen=window_size)
        self.alerts: list[str] = []
        self.n_processed = 0

    def process_reading(
        self, energy_kwh: float, timestamp: str, machine_id: str
    ) -> list[str]:
        self.window.append(energy_kwh)
        self.n_processed += 1
        active: list[str] = []

        # Alert 1: SPC Violation
        if (energy_kwh > self.spc["robust_upper"]
                or energy_kwh < self.spc["robust_lower"]):
            active.append(
                f"🚨 SPC VIOLATION [{machine_id}] {timestamp}: "
                f"{energy_kwh:.3f} kWh  "
                f"(batas {self.spc['robust_lower']:.2f}–{self.spc['robust_upper']:.2f})"
            )

        # Alert 2: EWMA Trend
        if len(self.window) >= 5:
            recent = np.array(list(self.window)[-5:])
            ewma_val = float(recent[-1] * 0.2 + recent[:-1].mean() * 0.8)
            if ewma_val > self.spc["UCL_ewma"]:
                active.append(
                    f"📈 EWMA TREND UP [{machine_id}] {timestamp}: "
                    f"EWMA={ewma_val:.3f} > UCL={self.spc['UCL_ewma']:.3f}"
                )

        # Alert 3: Rapid Rate-of-Change
        if len(self.window) >= 2:
            roc = abs(list(self.window)[-1] - list(self.window)[-2])
            threshold = self.spc["sigma_est"] * 2.5
            if roc > threshold:
                active.append(
                    f"⚡ RAPID CHANGE [{machine_id}] {timestamp}: "
                    f"Δ={roc:.3f} kWh  (threshold={threshold:.3f})"
                )

        self.alerts.extend(active)
        return active

    def get_summary(self) -> dict:
        return {
            "total_processed": self.n_processed,
            "total_alerts":    len(self.alerts),
            "alert_rate":      len(self.alerts) / max(1, self.n_processed),
            "recent_alerts":   self.alerts[-5:],
        }


def simulate_streaming(
    df: pd.DataFrame,
    spc_result: dict,
    machine_id: str = "M01",
    n_stream: int = 300,
) -> StreamingAlertEngine:
    """Jalankan simulasi streaming real-time pada data terakhir."""
    mdf = df[df["machine_id"] == machine_id].tail(n_stream).reset_index(drop=True)
    engine = StreamingAlertEngine(spc_result)
    for _, row in mdf.iterrows():
        engine.process_reading(
            row["Y_energy_kWh"], str(row["timestamp"]), machine_id
        )
    s = engine.get_summary()
    print(f"📡 [Streaming Engine] Diproses: {s['total_processed']} pembacaan")
    print(f"   Total alert: {s['total_alerts']} (rate: {s['alert_rate']*100:.1f}%)")
    if s["recent_alerts"]:
        for a in s["recent_alerts"][-3:]:
            print(f"   {a}")
    print()
    return engine


# ─────────────────────────────────────────────────────────────────
# MODUL 8: VISUALISASI DIGITAL TWIN DASHBOARD (UPGRADE)
# ─────────────────────────────────────────────────────────────────

def visualize_digital_twin(
    df: pd.DataFrame,
    anom_df: pd.DataFrame,
    spc_result: dict,
    model_result: dict,
    opt_result: dict,
    stress_df: pd.DataFrame,
    machine_id: str = "M01",
    save_path: str = "ecosense_dashboard_v2.png",
) -> None:
    """
    [UPGRADE v2] Dashboard 12 panel (v1: 7 panel).
    Panel baru: CUSUM, EWMA, Pareto Front, Feature Importance (permutation),
    Anomaly Detector Comparison.
    """
    mdf = anom_df[anom_df["machine_id"] == machine_id].reset_index(drop=True)

    fig = plt.figure(figsize=(22, 16))
    fig.patch.set_facecolor("#080c12")
    gs = gridspec.GridSpec(4, 4, figure=fig, hspace=0.50, wspace=0.38)

    C = {
        "blue":   "#4FC3F7", "green":  "#69F0AE", "red":    "#FF5252",
        "orange": "#FFB74D", "purple": "#CE93D8", "teal":   "#4DB6AC",
        "yellow": "#FFF176", "bg":     "#0d1420", "text":   "#E8EAF6",
        "border": "#1e2a3a",
    }

    def style(ax, title="", xlabel="", ylabel=""):
        ax.set_facecolor(C["bg"])
        ax.tick_params(colors=C["text"], labelsize=7.5)
        for sp in ax.spines.values():
            sp.set_edgecolor(C["border"])
        if title:
            ax.set_title(title, color=C["text"], fontsize=9,
                         fontweight="bold", pad=5)
        if xlabel:
            ax.set_xlabel(xlabel, color=C["text"], fontsize=8)
        if ylabel:
            ax.set_ylabel(ylabel, color=C["text"], fontsize=8)

    # ── P1: Energy Stream + Ensemble Anomaly ──
    ax1 = fig.add_subplot(gs[0, :2])
    style(ax1, f"⚡ Energy Stream Real-time – {machine_id}", ylabel="kWh")
    n_disp = min(600, len(mdf))
    e_disp = mdf["Y_energy_kWh"].values[-n_disp:]
    a_disp = mdf["anomaly_ensemble"].values[-n_disp:]
    ax1.plot(e_disp, color=C["blue"], lw=0.7, alpha=0.9, label="Energy")
    ax1.scatter(np.where(a_disp)[0], e_disp[np.where(a_disp)[0]],
                s=18, c=C["red"], zorder=5,
                label=f"Ensemble Anomaly ({a_disp.sum()})")
    ax1.axhline(spc_result["robust_upper"], color=C["orange"],
                ls="--", lw=1, label="Robust UCL")
    ax1.axhline(spc_result["robust_lower"], color=C["orange"],
                ls="--", lw=1, label="Robust LCL")
    ax1.legend(facecolor=C["bg"], labelcolor=C["text"], fontsize=7)

    # ── P2: CUSUM Chart (baru) ──
    ax2 = fig.add_subplot(gs[0, 2])
    style(ax2, "CUSUM Control Chart", ylabel="Cumulative Sum")
    cx = np.arange(len(spc_result["cusum_pos"]))
    ax2.plot(cx, spc_result["cusum_pos"],  color=C["green"], lw=0.8, label="C⁺")
    ax2.plot(cx, -spc_result["cusum_neg"], color=C["red"],   lw=0.8, label="C⁻")
    ax2.axhline( spc_result["cusum_threshold"], color=C["orange"], ls="--", lw=1, label="H")
    ax2.axhline(-spc_result["cusum_threshold"], color=C["orange"], ls="--", lw=1)
    ax2.legend(facecolor=C["bg"], labelcolor=C["text"], fontsize=7)

    # ── P3: EWMA Chart (baru) ──
    ax3 = fig.add_subplot(gs[0, 3])
    style(ax3, "EWMA Control Chart", ylabel="EWMA Value")
    ew_x = np.arange(len(spc_result["ewma"]))
    ax3.plot(ew_x, spc_result["ewma"], color=C["purple"], lw=0.8, label="EWMA")
    ax3.axhline(spc_result["UCL_ewma"], color=C["red"],  ls="--", lw=1, label="UCL")
    ax3.axhline(spc_result["LCL_ewma"], color=C["teal"], ls="--", lw=1, label="LCL")
    ax3.legend(facecolor=C["bg"], labelcolor=C["text"], fontsize=7)

    # ── P4: Actual vs Predicted ──
    ax4 = fig.add_subplot(gs[1, 0])
    style(ax4, "Ensemble: Aktual vs Prediksi", "Aktual (kWh)", "Prediksi (kWh)")
    ax4.scatter(model_result["y_test"], model_result["y_pred_test"],
                s=4, alpha=0.3, c=C["blue"])
    lims = [min(model_result["y_test"].min(), model_result["y_pred_test"].min()),
            max(model_result["y_test"].max(), model_result["y_pred_test"].max())]
    ax4.plot(lims, lims, color=C["green"], lw=1.5,
             label=f"R²={model_result['r2_test']:.4f}")
    ax4.legend(facecolor=C["bg"], labelcolor=C["text"], fontsize=8)

    # ── P5: Permutation Feature Importance (baru) ──
    ax5 = fig.add_subplot(gs[1, 1])
    style(ax5, "Feature Importance (Permutation)")
    imp = model_result["importance"]
    items = sorted(imp.items(), key=lambda x: abs(x[1]))
    names, vals = zip(*items)
    clrs5 = [C["red"] if v < 0 else C["green"] for v in vals]
    ax5.barh(names, vals, color=clrs5, alpha=0.85)
    ax5.axvline(0, color=C["text"], lw=0.5)
    ax5.tick_params(axis="y", labelsize=7)

    # ── P6: Pareto Front (baru) ──
    ax6 = fig.add_subplot(gs[1, 2])
    style(ax6, "Pareto Front (Multi-Obj Opt)", "Energi (kWh)", "Production Index")
    pf  = opt_result["pareto_front"]
    pf_e = [p[3] for p in pf]
    pf_p = [p[4] for p in pf]
    ax6.scatter(pf_e, pf_p, s=12, alpha=0.6, c=C["blue"], label="Pareto")
    bp = opt_result["best_point"]
    ax6.scatter(bp["energy"], bp["production_index"],
                s=150, c=C["red"], marker="*", zorder=10,
                label=f"Best: {bp['energy']:.2f} kWh")
    ax6.legend(facecolor=C["bg"], labelcolor=C["text"], fontsize=7)

    # ── P7: Digital Twin Comparison ──
    ax7 = fig.add_subplot(gs[1, 3])
    style(ax7, f"Digital Twin: Hemat {opt_result['saving_pct']:.1f}%")
    params = ["Suhu\n(°C)", "Beban\n(%)", "RPM\n(/100)"]
    curr   = [opt_result["current"]["temp"], opt_result["current"]["load"],
              opt_result["current"]["rpm"] / 100]
    optv   = [round(bp["temp"], 1), round(bp["load"], 1), round(bp["rpm"] / 100, 1)]
    x = np.arange(len(params))
    ax7.bar(x - 0.2, curr, 0.4, label="Saat Ini", color=C["orange"], alpha=0.85)
    ax7.bar(x + 0.2, optv, 0.4, label="Optimal",  color=C["green"],  alpha=0.85)
    ax7.set_xticks(x)
    ax7.set_xticklabels(params, color=C["text"], fontsize=7.5)
    ax7.legend(facecolor=C["bg"], labelcolor=C["text"], fontsize=7)
    ax7.set_title(
        f"Hemat {opt_result['saving_pct']:.1f}% "
        f"≈ Rp {opt_result['annual_saving_idr']/1e9:.2f}M/thn",
        color=C["yellow"], fontsize=8, fontweight="bold"
    )

    # ── P8: Residual Plot ──
    ax8 = fig.add_subplot(gs[2, 0])
    style(ax8, "Residual Plot (Ensemble)", "Fitted Values", "Residuals")
    res = model_result["residuals"]
    ax8.scatter(model_result["y_pred_test"], res, s=4, alpha=0.3, c=C["orange"])
    ax8.axhline(0, color=C["green"], lw=1.5)
    ax8.axhline( 2 * res.std(), color=C["red"], ls="--", lw=1, label="±2σ")
    ax8.axhline(-2 * res.std(), color=C["red"], ls="--", lw=1)
    ax8.legend(facecolor=C["bg"], labelcolor=C["text"], fontsize=8)

    # ── P9: Anomaly Detector Comparison (baru) ──
    ax9 = fig.add_subplot(gs[2, 1])
    style(ax9, "Anomaly Detector Comparison", ylabel="Jumlah")
    detectors = ["IForest", "LOF", "Z-Score", "Ensemble"]
    counts = [int(mdf["anomaly_iforest"].sum()), int(mdf["anomaly_lof"].sum()),
              int(mdf["anomaly_zscore"].sum()), int(mdf["anomaly_ensemble"].sum())]
    clrs9  = [C["blue"], C["purple"], C["teal"], C["red"]]
    bars9  = ax9.bar(detectors, counts, color=clrs9, alpha=0.85)
    for b, v in zip(bars9, counts):
        ax9.text(b.get_x() + b.get_width() / 2, v + 1, str(v),
                 ha="center", color=C["text"], fontsize=8)
    ax9.tick_params(axis="x", labelsize=7.5)

    # ── P10: X-bar Control Chart ──
    ax10 = fig.add_subplot(gs[2, 2])
    style(ax10, "X-bar Control Chart (SPC)", ylabel="Mean kWh")
    xbar = spc_result["xbar"]
    ax10.plot(xbar, color=C["blue"], lw=1, label="X-bar")
    ax10.axhline(spc_result["xbar_bar"], color=C["green"], lw=1.5, label="CL")
    ax10.axhline(spc_result["UCL_xbar"], color=C["red"],   ls="--", lw=1, label="UCL")
    ax10.axhline(spc_result["LCL_xbar"], color=C["red"],   ls="--", lw=1, label="LCL")
    ooc_x = np.where(spc_result["ooc_xbar"])[0]
    ax10.scatter(ooc_x, xbar[ooc_x], c=C["red"], s=30, zorder=5)
    ax10.legend(facecolor=C["bg"], labelcolor=C["text"], fontsize=7)

    # ── P11: Stress Test ──
    ax11 = fig.add_subplot(gs[2, 3])
    style(ax11, "Stress Test: Energi vs Produksi", "Kenaikan (%)", "kWh")
    scenarios = stress_df["Kenaikan Produksi (%)"].values
    energies  = stress_df["Energi (kWh)"].values
    clrs11 = [C["green"] if e == energies.min() else
              C["red"]   if e == energies.max() else C["orange"]
              for e in energies]
    b11 = ax11.bar(scenarios, energies, color=clrs11, alpha=0.85, width=6)
    for bar, val in zip(b11, energies):
        ax11.text(bar.get_x() + bar.get_width() / 2,
                  bar.get_height() + 0.2,
                  f"{val:.1f}", ha="center", color=C["text"], fontsize=7)
    ax11.set_xticks(scenarios)
    ax11.set_xticklabels([f"+{s}%" for s in scenarios], fontsize=7, color=C["text"])

    # ── P12: Shift & Machine Summary ──
    ax12 = fig.add_subplot(gs[3, :])
    style(ax12, "Rata-rata Konsumsi Energi per Shift & Mesin", ylabel="kWh")
    pivot = df.groupby(["machine_id", "shift"])["Y_energy_kWh"].mean().unstack()
    x12 = np.arange(len(pivot))
    width = 0.25
    shift_colors = [C["blue"], C["orange"], C["purple"]]
    for i, shift in enumerate(pivot.columns):
        ax12.bar(x12 + i * width, pivot[shift].values,
                 width, label=f"Shift {shift}", color=shift_colors[i], alpha=0.85)
    ax12.set_xticks(x12 + width)
    ax12.set_xticklabels(pivot.index, color=C["text"], fontsize=9)
    ax12.legend(facecolor=C["bg"], labelcolor=C["text"], fontsize=8)

    # Judul utama
    fig.text(0.5, 0.985,
             "EcoSense v2.0 — IoT Energy Optimization Digital Twin",
             ha="center", color=C["text"], fontsize=15, fontweight="bold")
    fig.text(0.5, 0.968,
             "AHM Manufacturing | Ensemble ML · CUSUM/EWMA SPC · NSGA-II Multi-Obj Opt · Streaming Alert",
             ha="center", color="#8899AA", fontsize=9)

    out = CFG.output_dir / save_path
    plt.savefig(str(out), dpi=140, bbox_inches="tight", facecolor="#080c12")
    plt.close(fig)
    print(f"📊 Dashboard EcoSense v2.0 disimpan: {out}\n")


# ─────────────────────────────────────────────────────────────────
# MODUL 9: EXPORT LAPORAN
# ─────────────────────────────────────────────────────────────────

def export_report(
    df: pd.DataFrame,
    model_result: dict,
    spc_result: dict,
    opt_result: dict,
    stress_df: pd.DataFrame,
    anom_summary: dict,
    alert_engine: StreamingAlertEngine,
) -> Path:
    summary = {
        "platform":          "EcoSense v2.0",
        "data_points":       int(len(df)),
        "n_machines":        int(df["machine_id"].nunique()),
        "ensemble_model":    "VotingRegressor (Ridge+RF+HGB)",
        "r2_test":           round(model_result["r2_test"], 4),
        "mae_test":          round(model_result["mae_test"], 4),
        "rmse_test":         round(model_result["rmse_test"], 4),
        "anomaly_detector":  "Ensemble (IForest+LOF+ZScore) voting",
        "anomaly_count":     anom_summary["count"],
        "anomaly_f1":        round(anom_summary["f1"], 4),
        "spc_charts":        ["X-bar/S", "CUSUM", "EWMA"],
        "cusum_ooc":         int(spc_result["cusum_ooc"].sum()),
        "ewma_ooc":          int(spc_result["ewma_ooc"].sum()),
        "optimization":      opt_result["method"],
        "pareto_solutions":  len(opt_result["pareto_front"]),
        "saving_pct":        round(opt_result["saving_pct"], 2),
        "annual_saving_idr": int(opt_result["annual_saving_idr"]),
        "streaming_alerts":  alert_engine.get_summary()["total_alerts"],
    }
    path = CFG.output_dir / "ecosense_v2_executive_summary.json"
    with path.open("w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2, ensure_ascii=False)
    return path


# ─────────────────────────────────────────────────────────────────
# MODUL 10: PIPELINE UTAMA
# ─────────────────────────────────────────────────────────────────

def run_ecosense_pipeline(
    target_machine: str = "M01",
) -> dict:
    """
    Pipeline lengkap EcoSense v2.0:
    1.  IoT multi-mesin (7 hari, 6 fitur sensor)
    2.  Ensemble Energy Model (VotingRegressor + Permutation Importance)
    3.  Anomaly Ensemble (IForest + LOF + Z-Score + voting + F1 score)
    4.  Advanced SPC (X-bar + CUSUM + EWMA)
    5.  Multi-Objective Optimization (NSGA-II / Pareto front)
    6.  Stress Test (7 skenario + degradasi efisiensi)
    7.  Streaming Alert Engine (3 jenis alert real-time)
    8.  Unified Dashboard (12 panel)
    9.  JSON Export
    """
    print("=" * 65)
    print("  EcoSense v2.0 – IoT Energy Optimization Digital Twin")
    print("  AHM Manufacturing | Ensemble ML + NSGA-II + CUSUM/EWMA")
    print("=" * 65 + "\n")

    # 1. Simulasi data IoT
    print("📡 [1/7] Simulasi data IoT multi-mesin (7 hari, 6 sensor)...")
    df = generate_iot_sensor_data()

    # 2. Ensemble Energy Model
    print("🔬 [2/7] Membangun Ensemble Energy Model...")
    model_result = build_energy_model(df, machine_id=target_machine)

    # 3. Anomaly Detection Ensemble
    print("🔎 [3/7] Anomaly Detection Ensemble (IForest + LOF + Z-Score)...")
    anom_df, anom_summary = detect_sensor_anomalies(df, machine_id=target_machine)

    # 4. Advanced SPC
    print("📊 [4/7] Advanced SPC (X-bar + CUSUM + EWMA)...")
    energy_vals = df[df["machine_id"] == target_machine]["Y_energy_kWh"].values
    spc_result = calculate_control_limits(energy_vals)

    # 5. Multi-Objective Optimization
    print("🎯 [5/7] Multi-Objective Optimization (NSGA-II / Pareto)...")
    opt_result = optimize_machine_settings(model_result)

    # 6. Stress Test
    print("⚡ [6/7] Stress Test (7 skenario, termasuk degradasi efisiensi)...")
    stress_df = stress_test_simulation(model_result, production_increase_pct=20)

    # 7. Streaming Alert Engine
    print("📡 [7/7] Streaming Alert Engine (real-time simulation)...")
    alert_engine = simulate_streaming(df, spc_result, machine_id=target_machine)

    # Ringkasan
    print(f"{'═'*65}")
    print("  RINGKASAN EKSEKUTIF – EcoSense v2.0")
    print(f"{'═'*65}")
    print(f"  Target Mesin              : {target_machine}")
    print(f"  Ensemble Model (R²)       : {model_result['r2_test']:.4f}")
    print(f"  Anomali Ensemble (F1)     : {anom_summary['f1']:.3f}  "
          f"({anom_summary['count']} titik)")
    print(f"  CUSUM Out-of-Control      : {spc_result['cusum_ooc'].sum()} titik")
    print(f"  EWMA  Out-of-Control      : {spc_result['ewma_ooc'].sum()} titik")
    print(f"  Metode Optimasi           : {opt_result['method']}")
    print(f"  Pareto Solutions          : {len(opt_result['pareto_front'])}")
    print(f"  Penghematan Energi        : {opt_result['saving_pct']:.2f}%")
    print(f"  Estimasi Hemat Tahunan    : "
          f"Rp {opt_result['annual_saving_idr']/1e9:.3f} Miliar")
    print(f"  Streaming Alerts          : {alert_engine.get_summary()['total_alerts']}")
    print(f"{'═'*65}\n")

    # Dashboard
    print("📈 Membuat Dashboard (12 panel)...")
    visualize_digital_twin(
        df, anom_df, spc_result, model_result,
        opt_result, stress_df, machine_id=target_machine,
    )

    # Export JSON
    report_path = export_report(
        df, model_result, spc_result, opt_result,
        stress_df, anom_summary, alert_engine,
    )
    print(f"📁 Laporan JSON: {report_path}")
    print("✅ EcoSense v2.0 Pipeline selesai!")

    return {
        "df": df, "anom_df": anom_df,
        "model_result": model_result,
        "spc_result": spc_result,
        "opt_result": opt_result,
        "stress_df": stress_df,
        "anom_summary": anom_summary,
        "alert_engine": alert_engine,
    }


# ─────────────────────────────────────────────────────────────────
# ENTRY POINT
# ─────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="EcoSense v2.0 – IoT Energy Optimization")
    parser.add_argument("--machine", default="M01",
                        help="Target machine ID: M01, M02, atau M03")
    args = parser.parse_args(args=[])

    run_ecosense_pipeline(target_machine=args.machine)